import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Flashcard, Note } from '../types';

export async function exportNoteToPDF(note: Note, flashcards: Flashcard[]) {
    const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #1e293b; }
          h1 { color: #0f172a; margin-bottom: 8px; border-bottom: 2px solid #3b82f6; padding-bottom: 12px; }
          .meta { color: #64748b; font-size: 14px; margin-bottom: 30px; }
          .content { line-height: 1.6; font-size: 16px; margin-bottom: 40px; white-space: pre-wrap; }
          .section-title { font-size: 20px; font-weight: bold; margin-bottom: 20px; color: #2563eb; }
          .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; margin-bottom: 15px; }
          .question { font-weight: bold; color: #334155; margin-bottom: 5px; }
          .answer { color: #475569; }
        </style>
      </head>
      <body>
        <h1>${note.title}</h1>
        <div class="meta">Created on: ${new Date(note.createdAt).toLocaleDateString()}</div>
        
        <div class="content">${note.content}</div>
        
        ${flashcards.length > 0 ? `
          <div class="section-title">Flashcards</div>
          ${flashcards.map(card => `
            <div class="card">
              <div class="question">Q: ${card.question}</div>
              <div class="answer">A: ${card.answer}</div>
            </div>
          `).join('')}
        ` : ''}
        
        <div style="margin-top: 50px; text-align: center; color: #94a3b8; font-size: 12px;">
          Generated by Smart Notes + Memory Booster
        </div>
      </body>
    </html>
  `;

    try {
        const { uri } = await Print.printToFileAsync({ html });
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
        console.error('Failed to export PDF:', error);
        throw error;
    }
}
